### PR TITLE
Many security patches

### PR DESCRIPTION
**Pull request by SkewedZeppelin**
Not all of them are relevant.
Compiles & boots.

I can do this for the others if wanted, although I cannot test for them.

### CODE REVIEW

**Comment by thestinger** [comment]
Not all of the changes that I made before are still wanted, especially in the original form. Some of that needs to be adjusted. I can't merge it all as it exists. I also don't know how you've chosen or applied the other patches and I can't realistically review it like this. It needs to be done differently than just submitting a long list of commits which I can't properly review.

**Comment by thestinger** [comment]
So for example, b3a3169 cannot be applied because it will break Go. It needs to be handled differently now that Go uses brk in a silly way to place their own heap. They don't actually use the brk heap but they use the system call to fetch a reasonable address.

**Comment by thestinger** [comment]
5ba7ee8 is being handled via init.rc (along with similar sysctl options) since that makes more sense than needing per-kernel patches.

**Comment by thestinger** [comment]
This needs to be done bit-by-bit, in a way that's easier for me to review and comment on. The cherry-picking of upstream patches should ideally be done by giving me a git cherry-pick command to update to the latest upstream LTS revision along with giving instructions on how to resolve each conflict. That's something I can much more realistically review. If you want to cherry-pick more in addition to the latest upstream changes it should be done bit-by-bit, making sure that each patch is required and applies properly.

Focus should also be on the Pixel 3 and Pixel 3a rather than the previous device generations, and especially not the Pixel and Pixel XL. The upstream kernel branch used by the Pixel 2 and 3 is going to receive 6 years of upstream support. The branch used by the Pixel 1 is already dead, and there's not much that can realistically be done about it with the resources available. Pixel and Pixel XL are considered deprecated, legacy devices by GrapheneOS for various reasons and it's not really worth spending time working on those. Pixel 2 and 2 XL are at least not a hopeless cause but focus should be on the current generation devices.

The order to handle the devices is 3 = 3a > 2 > 1, and 1 doesn't really qualify for device-specific work at this point with the limited resources of the project. There's a reason that there are fewer downstream changes. I also have no intention of backporting type-based CFI and ShadowCallStack which are implemented for the Pixel 3 and 3a and are among the most useful hardening features.

**Comment by SkewedZeppelin** [comment]
Completely understandable.

> I can't merge it all as it exists.

Too hasty of me.

> chosen or applied the other patches

using an [automated patcher](https://gitlab.com/divested-mobile/cve_checker)
and [patches](https://gitlab.com/divested-mobile/kernel_patches/blob/master/Kernel_CVE_Patch_List.txt)

> b3a3169 cannot be applied because it will break Go

curious about this
I just tested Syncthing on a device with that patch applied and it works fine.
Is there a more specific case?

I basically agree with everything else mentioned.

**Comment by thestinger** [comment]
It depends on which version of Go they're using. Some versions of Go use the brk system call in the heap implementation and crash if the system call returns an error. It shouldn't do that, and it should handle errors with a fallback approach, but I cannot include that attack surface reduction anymore without breaking real world apps.

**Comment by thestinger** [comment]
@SkewedZeppelin It would be best to start with a cherry-pick of all the stable kernel commits, which will need to be carefully handled and tested. Once those are all applied again, it makes sense to backport more patches. I want to start with the 3 and 3a though. I edited my last comment to clarify that the 3 and 3a are equal priority, followed by the 2 and then the 1 last of all.

**Comment by thestinger** [comment]
For branches that are still maintained upstream, missing patches can also be reported upstream after applying them downstream.

**Comment by thestinger** [comment]
@SkewedZeppelin I would recommend looking at the work maintained by https://github.com/nathanchance as a starting point and consider contacting him about it.

**Comment by thestinger** [comment]
You can see that I have a 10-stable-base branch for each of the kernels. I'd like to use @nathanchance's to have those as an up-to-date base with all of the stable patches merged. I would prefer to have this as a clean set of cherry-picked patches which is regenerated as needed.

**Pull request closed without merging**
